apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: books
    app.kubernetes.io/instance: books-instance
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: backend
    app.kubernetes.io/managed-by: kubectl
  name: books
spec:
  selector:
    app: books
  type: LoadBalancer
  ports:
   -  protocol: TCP
      port: 80
      targetPort: 7000
